### ISSUE TITLE
License / Copyright?

### ISSUE THREAD

**Issue by tianon** [Shopify/logrus-bugsnag#7]
This repo appears to be missing any notion of what the license is. :smile:

I would _assume_ it's Expat (same as Logrus; https://github.com/Sirupsen/logrus/blob/master/LICENSE), since it moved here from Logrus's repo, but I'd rather be sure. :+1:

Thanks!

**Comment by tianon** [comment]
cc @burke @csfrancis @Roxot

**Comment by burke** [comment]
Thanks for pointing this out: 5a46080c635f13e8b60c24765c19d62e1ca8d0fb

**Comment by tianon** [comment]
Rock on, thanks @burke! :heart:

**Comment by burke** [comment]
fyi @Sirupsen
